### ISSUE TITLE
Issues with aicspylibczi for latest version of Python

### ISSUE THREAD

**Issue by rdemets** [Tom-top/cmlite#1]
Hi Thomas, 

I had to modify the yml file to force the version of python==3.11 as aicspylibczi is not yet compatible with python 3.12 (default). 
The installation works just fine once the dependencies adjusted. Still yet to be tested.

Thanks. Regards, Richard.

**Comment by Tom-top** [comment]
Hi Richard,

Yes, thanks for noticing this, I will update the env yml file. I still have a few changes to add, especially on the analysis side for it to be fully functional. I will let you know when it is ready to go. Hopefully within this week or so :)

Tom
